### ISSUE TITLE
[Bug]: Connection reset by peer when clicking op "Load" on the Device Imports screen

### ISSUE THREAD

**Issue by litebito** [Onemind-Services-LLC/netbox-metatype-importer#25]
### NetBox plugin version

v0.3.0

### NetBox version

Current: v3.7.1

But same issue for versions v3.7.0, v3.6.0, v3.5.3, ...

### Steps to Reproduce

Centos Stream 8
The server has a system wide proxy set :
In /etc/environment:

```
http_proxy=http://httppxxxx.srv.xxx.com:8080
https_proxy=http://httppxxxx.srv.xxx.com:8080
no_proxy=127.0.0.1,localhost
```

in Netbox Config:

```
HTTP_PROXIES = {
     'http': 'http://httppxxxx.srv.xxx.com:8080',
     'https': 'http://httppxxxx.srv.xxx.com:8080'
}


   'netbox_metatype_importer': {
            'github_token': '[mygithubtoken]'
```
In Netbox, with the plugin installed, clicking op "Load" on the Device Imports screen

### Expected Behavior

the list of device types would load

### Observed Behavior

Error message:

Server Error
There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'requests.exceptions.ConnectionError'>

('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

Python version: 3.11.5
NetBox version: 3.7.0

**Comment by abhi1693** [comment]
This does not look like an issue with the plugin unless you can provide detailed steps to reproduce it. Please recheck your deployment and make sure that the repo that you are trying to access is allowed via your proxy.

**Comment by litebito** [comment]
I can access the repo through the proxy
(tested with wget)

**Comment by abhi1693** [comment]
Could you give detailed information about your setup? Because I'm unable to reproduce this with a simple setup connecting to GitHub via a proxy.

**Comment by litebito** [comment]
Hi,

I updated the initial info:
- I now can use a systemwide proxy which does not need authentication
- updated netbox and plugin version

Testing:

```
curl https://raw.githubusercontent.com/netbox-community/devicetype-library/master/device-types/Cisco/2951-ISR.yaml
---
manufacturer: Cisco
model: 2951 ISR
part_number: CISCO2951/K9
slug: cisco-2951-isr
u_height: 2
is_full_depth: true
console-ports:
  - name: con 0
    type: rj-45
power-ports:
  - name: PS-1
    type: iec-60320-c14
    allocated_draw: 70
    maximum_draw: 340
interfaces:
  - name: GigabitEthernet0/0
    type: 1000base-t
  - name: GigabitEthernet0/1
    type: 1000base-t
  - name: GigabitEthernet0/2
    type: 1000base-t
```
