### ISSUE TITLE
<class 'TypeError'>  cannot unpack non-iterable Exception object

### ISSUE THREAD

**Issue by litebito** [Onemind-Services-LLC/netbox-metatype-importer#66]
Hi,

since the last time I used the plugin without issues a few months ago, I now get this result if I click the Load button
it happens with both 
DeviceType Imports
ModuleType Imports

```
<class 'TypeError'>

cannot unpack non-iterable Exception object

Python version: 3.12.9
NetBox version: 4.2.7
Plugins: 
  aggregatron: 0.1
  netbox_attachments: 7.2.0
  netbox_device_view: 0.1.9
  netbox_dns: 1.2.7
  netbox_documents: 0.7.2
  netbox_floorplan: 0.6.0
  netbox_inventory: 2.3.0
  netbox_ip_monitor: 0.0.0
  netbox_ipcalculator: 1.4.9
  netbox_metatype_importer: 0.6.0
  netbox_qrcode: 0.0.17
  netbox_reorder_rack: 1.1.3
  netbox_security: 1.0.4
  netbox_topology_plugin: 0.14.3
  netbox_topology_views: 4.2.1
```

Any idea's ? Any extra info I can provide to assist troubleshooting?
